spring.application.name=CarbonFootprintTracker

spring.datasource.url=jdbc:postgresql://localhost:5432/carbon_tracker
spring.datasource.username=umeshchand
spring.datasource.password=Zssuc$20
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.ai.ollama.base-url=http://localhost:11434

spring.ai.model.chat=ollama
spring.ai.ollama.chat.options.model=codellama:latest

spring.ai.model.embedding=ollama
spring.ai.ollama.embedding.options.model=nomic-embed-text



spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=768